apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-webapp
parameters:
  staleReplicaTimeout: '30'
provisioner: driver.longhorn.io
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
