---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 5m
  chart:
    spec:
      chart: longhorn
      version: 1.7.2
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
      interval: 5m
  values:
    env:
      TZ: "America/New_York"
    persistence:
      defaultClassReplicaCount: 1
    longhornUI:
      replicas: 1
    ingress:
      enabled: true
      ingressClassName: internal
      host: longhorn.internal.${SECRET_DOMAIN}
