apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:P04UWjzkJJxw9gaDXHTU5KBqlKbXi9Ma1W61oiTuypmgwqI2WvFREg==,iv:mhCc1vKsANZQQgGE4a+cy1da/2N1mtsp7KTREBfD26I=,tag:PB45XhmfLB1QcCP1wPieXQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pjzz8yxguh6ucsc9zc94chspcdgm5yfp9wy5q5ayxpll23jakadq7e633r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBcy9YZ0J6RGs2Y1VWL1Nx
            RkdOYmlpNVhTLzN2ZzVMaEgwaTFBakVhQlRRCkNBSWNueWNkcXBvcXBoMHFjUkZY
            TmdGeDhoekZtUEVlRjVSNG5KcERDNncKLS0tIEZDR1IzdTY0RmVRMjgwUFdwaFJW
            SFhRTXp3bXc1TktGSWt2SWVXM3lRR2cKDrktW/BSJ3YdG/pleGgI8oBbU1HTyvZZ
            yEnX73bmlJW0QKl6SF06NJUW5jazSF2RwVOlyctAPylu5D3jHAsfOA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-05T21:30:46Z"
    mac: ENC[AES256_GCM,data:jHkw+b56Oefazl2Js4LwMYvuvkSv5Q2iXggIF4TaZ/piAEpiImxjPAgjsaEgtY6km4gTSKyDzpd5B9KjDRyEoKD6B8oZaPcu098JqYD1C2WlAnGYXBBPWw64ocb1s8CBhWzhF013D6OEZadjB0IP51xciel7QYfvdsBGZq5LPYg=,iv:BGdow9+NUM6zMhzkH51OjkeMU7NZZZPpZJX1jzoCd5I=,tag:VOsGjdpJiNBYoWmaXKeLRg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
