apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-longhorn-webapp
  namespace: downloads
spec:
  resources:
    requests:
      storage: 15Gi
  volumeMode: Filesystem
  storageClassName: longhorn-webapp
  accessModes:
    - ReadWriteMany