---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plex
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 15m
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            runAsUser: 2000
            runAsGroup: 2000
            runAsNonRoot: true
            fsGroup: 2000
            fsGroupChangePolicy: Always
        containers:
          main:
            image:
              repository: ghcr.io/onedr0p/plex
              tag: 1.41.2.9200-c6bbc1b53@sha256:1f28b5e5a964481f80e76db3c986082d2fc3bca2d16d2742704e9adf8349c79c
            env:
              TZ: "${TIMEZONE}"
              ADVERTISE_IP: "https://{{ .Release.Name }}.${SECRET_DOMAIN}:443"
              HOSTNAME: "plex"
            envFrom:
              - secretRef:
                  name: plex-secret
            resources:
              requests:
                cpu: 100m
                memory: 2Gi
              limits:
                memory: 10Gi
    service:
      main:
        controller: main
        type: LoadBalancer
        ports:
          http:
            port: 32400
            protocol: TCP
    ingress:
      main:
        enabled: true
        className: external
        hosts:
          - host: "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: main
                  port: http
    persistence:
      config:
        type: nfs
        server: hetzner.${SECRET_DOMAIN}
        path: /storage/configs/plex/
        globalMounts:
         - path: /config
           readOnly: false
      media:
        type: nfs
        server: hetzner.${SECRET_DOMAIN}
        path: /storage/media
        globalMounts:
          - path: /data
      transcode:
        existingClaim: plex-cache
        advancedMounts:
          main:
            main:
              - path: /transcode
                readOnly: false
