apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-cache
  namespace: media
spec:
  resources:
    requests:
      storage: 30Gi
  volumeMode: Filesystem
  storageClassName: longhorn-webapp
  accessModes:
    - ReadWriteOnce