apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:0SRwjgcT/HQajzqVBkUyD7ivwCQMWaNMO2MHn3KR3ehqbmS6L3OQZQ==,iv:3HlGv9UinUykH2kiycRdneYJMph8UYbYIHVSsAgl0bc=,tag:fIHQtSTahIvpbEI5emK1tA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pjzz8yxguh6ucsc9zc94chspcdgm5yfp9wy5q5ayxpll23jakadq7e633r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0VkNTazhpbG5yeVFzSzAy
            OWpPVzZNREZZNkdDeVhISjh5ZEw3UHR3OVZJCmpWaVcweXBZU2p2R0NaWXZ3cE5j
            OFNuWnZqOCs3cklibktjZUdxdTJ6b3cKLS0tIGVZWGRKVnRKbEsyZzluQmNhL0Nl
            ZDNiVWpjWGV4ZVlBYUhMYXRnTllleVkKU5DtGGwvm3NgBMpItOg17SPg73vAvRIg
            Ht2Es1XF/pT/uszgFB6//uMyyTWLG5seTC9i+kA1Lz8Fw15FLN750A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-05T21:30:46Z"
    mac: ENC[AES256_GCM,data:zABDmxgzuz+m19SKpcQCj1oPdi3Zq8u+5xXmSnGBXleWGVRIYhIRrrXcgfTGQhHd8ZqrZa+5No6rhwiVNmr38trct3Kwzz3oGTFqis040MPzZk9ZAAy+hO0RzkKZEAE+PcjyNCWqqD20WEraVbxj3uM+BAr7m+YjjQMsGGXveFI=,iv:1a/spPyjEDDLYahgdtdBZMiZRuwGjXJpQ0P7dtND6Aw=,tag:YHUKQf2XNeoHtpm4g7IRhg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
