apiVersion: v1
kind: Namespace
metadata:
    name: external-secrets
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pjzz8yxguh6ucsc9zc94chspcdgm5yfp9wy5q5ayxpll23jakadq7e633r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSK1N4VWtwNThPSHpTMzRh
            bkZzTUNDcjcvS28wRndYR3RXenMrcm1hbkRBCjNlZFMzaVAzZUc2NkVpeVdQTUVw
            eThCVmRSVHViRUxJWnhLTCtGRFNlYU0KLS0tIHdabSt3V2l0L2ZUYm1qL2Z4cFEx
            TmpscTRvQ2JjcE9iTWRlSDRrV3o1N2sKq5m+AuMvH7NCXs4ScnzcI7hZDvE4clo8
            s18KVZh47eXkO3exVDo31ldtDyBnBYepPOu9vWP1ikrmP46jF8LHiQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-10T18:24:24Z"
    mac: ENC[AES256_GCM,data:U4JVEm5E8kZdZ9IH57dJzyUkhAIJc2s9oNVFVC762ch2jxVKpLNT5zJ4jouU3aD0dboVi42b9CYUg2zhPqf9p8ThIyoGR0yHp9Isk1n8w2V27K3k6UwJtAcRzhhDMimCTwCgCOhuesfX1VzmXCz53ZOb0h/BtwE5xpvxxIVX808=,iv:xggY6DPI/2MD8bch0QClrI8DWS9+2GeWwvrpze6yFP4=,tag:FIPuinx0z7rFu+qaqoPPPQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: onepassword-connect-secret
    namespace: external-secrets
stringData:
    1password-credentials.json: ENC[AES256_GCM,data:ypMcYtnWNT5nV6ZmAXk/JSGmuDic6Niq/LBQqz5t34D1CDD3LInsbhHbI+7x6NfR1zbdxjVBnFsbYhDLiHNSvN6tTADPiCoH+iW7HuNrH3SBuWvqSC2WNMZTXuM58YQS6ZGzOkm+ROWnkJcmuIYNOhSm1NdUDtS70OtvY+Ms882nf7bps/1+zSTxgG2Z7SRXI3Hr/JDSHfcvT4B9pKChGfbnWfBJiowyTjWwVN7XtNCecAPwIBv/W2KxiUXrq/eRJMyh6Y4FlZCBsrajMxdoH3wP8VDjdJxZvpjxaBECD5/NmkUK2DTJSJmrCtOHbBnh8OeZrN2yzVsDnBDteueyYq+m1owpHTMmFCJzT5OKEnuvgJ5kxcqG0m8qJj9XYVSEjVwRWjqXoFRDoBLKhEePWe1VhIfCo4DsDih+Xus60g2JiHpZPwSe2kAl2EHrovLM1SN98XpGCmGGjfLLZNGTM1zlG6oihtbYibCJKz48l9/N0IodoL/ZR0kvl3ahZaeb8GwY2Ev0xep2jAtec7V/8kzpbBPMZBRdnlj/qJFH8Cc0/0JL8lVe1w5oZB9tn93IAGP9ZCViPw4AS4Q2PHPP7+Ki6MSVGl02847E3dNaZZeL/dTKNXtaR+iLLWUtdNV1aOl9+eQxbZUcBm2EOdWoVgZ1P9LL2Je2BDZQVlfhJcdRMZ5UKwpr3xVKU53E61TyYerdJAujpzZQGFNShcT9JQQfvrUcqYE2MNPARULF4hTmLSAGnF8no/oz1WR8gxL3dVJtU/7aKt5FIdot4lcyL85UWeCY/LOBBZzSRjXKbmuZ7fZeK6h1jqeLtpcHNaLXUQvQE+lnXS+647KmEctcLVpBUuFjioXD/rgX7bS8wzP2ML9OIoHOTm2JPhRbp3oswHT71NPpSocPR7MMvXKe4L0I+lCORZCbg0eYTB9hMbi3VArrgvExu3TyXIhrMli3Y3gQ9BAjGSdysZF5AwV7W2/HFdwhKUtXKxcNbMWEoayCd1cy8u2rsGZt1wdia9Wr2zeoSepOaPz4uNrXvh9hMul93msJpo2gur/AZ6sz/R6U7TtIf3phaiHbwISpBQJ4ovygM9Kr9VNZsUZQX5cgNyTGnmHUlXaU2sN6a6wSKcwyX5xpFuxzyeEXUJpg0xOK2RrY01CTQmuqt1KxHsUg0KuDV6WTUnsUyN7F5gBhNoohfljnlnnOC3Z4Gxpff0N4Cpd0sjkHWfEgAPeIsyZph51jIEYXFhfdsDFcCGW+mDaNj9W66dH446ldEjJ+dU5uZ8rXnqU33R7wFRH4LhXMQwtEtRkzF5cRo3iOYfPP6HcT3fUVusEtdiwE55yAZgn1TsyLQuAzdfN0Lpxv4o5WbLFZGgb7Y0fREVJIw6JALF0ppY27HTqY7ZJ1GEytz5WuJyb+NQpvOrijoJyKAru8a2WFsKL4Nyn17VdQlcr0LUM1ZQ==,iv:kddgOxb8fV2B5yatI0w7xORhMIcBlOTjsOgfEI9JwIQ=,tag:IXLpevX1NnGIBeMjVU8UzQ==,type:str]
    token: ENC[AES256_GCM,data:U9rzfPUMIQCgGSn22NrvPa77tZtvYREaW4kfwQ2U/tcro8JVN2O/U4sJSEPrQglqU4u2X/DGSbQ+b47nfvdEl2dHpDWu7oQU9vXLBi8wUF+3eSgoCEphnwkzxWeNmP0SfDwqX8OOLO1l529/B+HDivGBR/xq7bT47rts2cJ7bsF2iO8MqqKqso4ocPgG0dO0QZpFeZQx8EFXZtIQ51i5ewByZze7rI8SICemyxJu2KzBy2WTRn85umhb/jY3SU6BicQDVitLaAVdthLEmRuNG5o6+/fsywSx+BJHcWtpw6ecB5ukWsq9z99VWaBF6+qEdEzrHfJGJrZGcHJ/l/ltpxWDxzPDegyod+pGww3gGQ/hkycgdosK7UtFm/3AIYID/zmYHqwELt7N5sOWmDgbuHLL9gh2PJtKy6kJy6vKp2mKQ+EnRGLZ6dQ/sDzc3njje4X5llPJTdyLwJmr3dW3w/gaRhfYOPmMcLEwmehg67u8RZbxdcCPuvAepIjtvkRnHqUj6B2241Fspq5anOcx2U89CnLzLQbbZPbDXXGGMU3Q9oEj4SVoiyuY0HApm1X6qqp0AJ8ahOEAZfTS2/xsDuQ3GCN2gn14PAOLvzBT/6JsvEi6r8YqNAeEZsZLsVLNskCsPUKyBWQ5N8OdZCB7BO4uTBkEMhBtZGVDCKspBWg8BLEV/TLRbABPgo6GG8xBQcRRRQMBIq3PY/4q2wQknV55M5lSdD93lXKAJIXQIwt+FCygTC/gf/m92Io2haLNYIlgGXAvMeFIMT0vkl3nQOeXT0mVuE6lCSWVbA7Y1GaLVjHi33iAqBN3htPJzOnuxWQSX0Ghfk03IxvqP+c8+uOe,iv:c695l903tdAow5xSprpTRVJVnjc+7KC1bDxPlh7zeDI=,tag:pxySVdkzgh3MSW2DDlZLIg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pjzz8yxguh6ucsc9zc94chspcdgm5yfp9wy5q5ayxpll23jakadq7e633r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSK1N4VWtwNThPSHpTMzRh
            bkZzTUNDcjcvS28wRndYR3RXenMrcm1hbkRBCjNlZFMzaVAzZUc2NkVpeVdQTUVw
            eThCVmRSVHViRUxJWnhLTCtGRFNlYU0KLS0tIHdabSt3V2l0L2ZUYm1qL2Z4cFEx
            TmpscTRvQ2JjcE9iTWRlSDRrV3o1N2sKq5m+AuMvH7NCXs4ScnzcI7hZDvE4clo8
            s18KVZh47eXkO3exVDo31ldtDyBnBYepPOu9vWP1ikrmP46jF8LHiQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-10T18:24:24Z"
    mac: ENC[AES256_GCM,data:U4JVEm5E8kZdZ9IH57dJzyUkhAIJc2s9oNVFVC762ch2jxVKpLNT5zJ4jouU3aD0dboVi42b9CYUg2zhPqf9p8ThIyoGR0yHp9Isk1n8w2V27K3k6UwJtAcRzhhDMimCTwCgCOhuesfX1VzmXCz53ZOb0h/BtwE5xpvxxIVX808=,iv:xggY6DPI/2MD8bch0QClrI8DWS9+2GeWwvrpze6yFP4=,tag:FIPuinx0z7rFu+qaqoPPPQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
